@startuml

scale max 1920 width
top to bottom direction

skinparam nodesep 12
skinparam ranksep 24
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Tahoma
skinparam defaultFontSize 12
skinparam roundCorner 6
skinparam dpi 150
skinparam arrowColor black
skinparam arrowThickness 0.5
skinparam packageTitleAlignment left

' oval
skinparam usecase {
  borderThickness 0.5
}

' rectangle
skinparam rectangle {
  borderThickness 0.5
}

' component
skinparam component {
  borderThickness 1
}


rectangle "collectable-handler" as _collectable_handler
rectangle "document-input-handler" as _document_input_handler
rectangle "gameController" as _gameController
rectangle "input-handler" as _input_handler
rectangle "key-code" as _key_code
rectangle "<b>main</b>" as _main
rectangle "sheep" as _sheep
rectangle "sheep-element" as _sheep_element


_document_input_handler ---> _input_handler
_document_input_handler ---> _key_code
_gameController --> _collectable_handler
_gameController --> _input_handler
_gameController --> _key_code
_gameController --> _sheep
_gameController --> _sheep_element
_input_handler --> _key_code
_main --[thickness=1]> _collectable_handler
_main --[thickness=1]> _document_input_handler
_main -[thickness=1]> _gameController
_main -[thickness=1]> _sheep
_main --[thickness=1]> _sheep_element

@enduml

' View and edit on https://arkit.pro