name: CD

on:
  push:
    branches:
      - "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localPath: './dist/*'
          remotePath: './'
